Repository rust-lang/www.rust-lang.org, pull requests merged in 2018-12, with the labels that each got.

#513 Fix clippy warnings, fix #511
  src/group.rs
  src/main.rs
  src/production.rs
  src/rust_version.rs
Labels: needs review, question

#528 fix(production.hbs): Vertically center logos in testimonials
  src/styles/app.scss
  templates/what/networking/production.hbs
Labels: needs review

#518 Mention `rustup upgrade` in install instructions
  templates/tools/install.hbs
Labels: changes requested, needs review

#527 Make top margin of footer columns consistent
  templates/footer.hbs
Labels: needs review, waiting on response

#514 Update youtube icon, fix 413
  static/images/youtube.svg
  templates/footer.hbs
Labels: needs review

#501 Add blurb before domains
  templates/panels/domains.hbs
Labels: needs review

#532 More quotes
  templates/learn/get-started.hbs
  templates/policies/media-guide.hbs
Labels: needs review

#530 fix(testimonials): Vertically align testimonials everywhere
  src/styles/app.scss
  templates/what/networking/production.hbs
Labels: needs review

#542 feat(styles): reduce intensity of yellow
  src/styles/app.scss
Labels: needs review

#540 feat(css): concat vendor css
  .gitignore
  src/main.rs
  static/styles/Skeleton-2.0.4/css/skeleton.css
  static/styles/Skeleton-2.0.4/images/favicon.png
  static/styles/Skeleton-2.0.4/index.html
  static/styles/skeleton.css
  templates/layout.hbs
Labels: needs review

#553 Improve consistency and bump text size.
  src/styles/app.scss
  templates/governance/index.hbs
  templates/panels/production.hbs
Labels: needs review

#574 feat(index): remove cal
  templates/panels/get-involved.hbs
Labels: needs review

#603 Switch preloading of fonts from ttf to woff to align with proper font…
  templates/layout.hbs
Labels: needs review

#596 reduce highlight block height from 30px to 24px
  src/styles/app.scss
Labels: waiting on response

#618 Fix width of nav link to the homepage
  src/styles/app.scss
  templates/nav.hbs
Labels: needs review

#597 Add redirects to keep old URIs working
  src/main.rs
  src/redirect.rs
Labels: needs review

#623 align elements better by modernizing page to new rules
  templates/what/embedded/get-started.hbs
  templates/what/embedded/pitch.hbs
Labels: needs review

#632 Fix style around Rust name
  src/styles/app.scss
  templates/nav.hbs
Labels: bug, design, needs review

#635 Add a design bug issue template
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/design_bug_report.md
Labels: chore, ops

#631 Improved design of footer links
  src/styles/app.scss
Labels: design, needs review

#630 Update Rocket to 0.4
  Cargo.lock
  Cargo.toml
  src/main.rs
  templates/governance/group.hbs
Labels: chore, dev, needs decision

#637 Don't use skeleton styles for buttons
  src/styles/app.scss
  static/styles/skeleton.css
  templates/index.hbs
Labels: design, needs review

#634 Add a link to 'getting started' from 'install'
  templates/tools/install.hbs
Labels: content, design, needs review

#633 Add a link to the playground from the getting started page
  templates/learn/get-started.hbs
Labels: content, needs review

#636 Don't allow getting component parts of templates
  src/main.rs
  templates/components/edition-banner.hbs
  templates/components/footer.hbs
  templates/components/languages-dropdown.hbs
  templates/components/layout.hbs
  templates/components/nav.hbs
  templates/components/panels/domains.hbs
  templates/components/panels/get-involved.hbs
  templates/components/panels/language-values.hbs
  templates/components/panels/production.hbs
  templates/components/tools/editors.hbs
  templates/components/tools/install-script.hbs
  templates/components/tools/rustup.hbs
  templates/components/what/cli/code-inputs.hbs
  templates/components/what/cli/code-main.hbs
  templates/components/what/cli/example.hbs
  templates/components/what/cli/maintainable.hbs
  templates/components/what/cli/pitch.hbs
  templates/components/what/cli/production.hbs
  templates/components/what/embedded/get-started.hbs
  templates/components/what/embedded/pitch.hbs
  templates/components/what/embedded/showcase.hbs
  templates/components/what/embedded/testimonials.hbs
  templates/components/what/networking/get-started.hbs
  templates/components/what/networking/pitch.hbs
  templates/components/what/networking/post-json.hbs
  templates/components/what/networking/production.hbs
  templates/components/what/networking/take-json.hbs
  templates/components/what/wasm/get-started.hbs
  templates/components/what/wasm/js.hbs
  templates/components/what/wasm/pitch.hbs
  templates/components/what/wasm/production.hbs
  templates/index.hbs
  templates/learn/get-started.hbs
  templates/tools/index.hbs
  templates/tools/install.hbs
  templates/what/cli.hbs
  templates/what/embedded.hbs
  templates/what/index.hbs
  templates/what/networking.hbs
  templates/what/wasm.hbs
Labels: dev
